#nullable enable
using Guna.UI2.WinForms;

namespace acaiGalatico.UI.Forms
{
    partial class frmPedidos
    {
        private System.ComponentModel.IContainer? components = null;
        private Guna2Panel pnlPagina;
        private Guna2Panel pnlCard;
        private Guna2Panel pnlHeader;
        private Guna2HtmlLabel lblTitulo;
        private Guna2HtmlLabel lblDescricao;
        private Guna2HtmlLabel lblResumo;
        private Guna2HtmlLabel lblApiInfo;
        private Guna2Button btnNovo;
        private Guna2Button btnAtualizar;
        private SplitContainer splitMain;
        private Guna2Panel pnlTabela;
        private Guna2Panel pnlEditor;
        private Guna2DataGridView dgvPedidos;
        private DataGridViewTextBoxColumn colId;
        private DataGridViewTextBoxColumn colData;
        private DataGridViewTextBoxColumn colStatus;
        private DataGridViewTextBoxColumn colCliente;
        private DataGridViewTextBoxColumn colTotal;
        private DataGridViewButtonColumn colEditar;
        private DataGridViewButtonColumn colExcluir;
        private Guna2HtmlLabel lblEditorTitulo;
        private Guna2HtmlLabel lblCodigo;
        private Guna2TextBox txtCodigo;
        private Guna2HtmlLabel lblData;
        private Guna2DateTimePicker dtpData;
        private Guna2HtmlLabel lblStatus;
        private Guna2ComboBox cboStatus;
        private Guna2HtmlLabel lblCliente;
        private Guna2ComboBox cboCliente;
        private Guna2HtmlLabel lblValor;
        private Guna2TextBox txtValor;
        private Guna2HtmlLabel lblPagamento;
        private Guna2ComboBox cboPagamento;
        private Guna2HtmlLabel lblEndereco;
        private Guna2TextBox txtEndereco;
        private Guna2HtmlLabel lblBairro;
        private Guna2TextBox txtBairro;
        private Guna2HtmlLabel lblObservacao;
        private Guna2TextBox txtObservacao;
        private Guna2Button btnSalvar;
        private Guna2Button btnExcluir;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            pnlPagina = new Guna2Panel();
            pnlCard = new Guna2Panel();
            splitMain = new SplitContainer();
            pnlTabela = new Guna2Panel();
            dgvPedidos = new Guna2DataGridView();
            colId = new DataGridViewTextBoxColumn();
            colData = new DataGridViewTextBoxColumn();
            colStatus = new DataGridViewTextBoxColumn();
            colCliente = new DataGridViewTextBoxColumn();
            colTotal = new DataGridViewTextBoxColumn();
            colEditar = new DataGridViewButtonColumn();
            colExcluir = new DataGridViewButtonColumn();
            pnlEditor = new Guna2Panel();
            btnExcluir = new Guna2Button();
            btnSalvar = new Guna2Button();
            txtObservacao = new Guna2TextBox();
            lblObservacao = new Guna2HtmlLabel();
            txtBairro = new Guna2TextBox();
            lblBairro = new Guna2HtmlLabel();
            txtEndereco = new Guna2TextBox();
            lblEndereco = new Guna2HtmlLabel();
            cboPagamento = new Guna2ComboBox();
            lblPagamento = new Guna2HtmlLabel();
            txtValor = new Guna2TextBox();
            lblValor = new Guna2HtmlLabel();
            cboCliente = new Guna2ComboBox();
            lblCliente = new Guna2HtmlLabel();
            cboStatus = new Guna2ComboBox();
            lblStatus = new Guna2HtmlLabel();
            dtpData = new Guna2DateTimePicker();
            lblData = new Guna2HtmlLabel();
            txtCodigo = new Guna2TextBox();
            lblCodigo = new Guna2HtmlLabel();
            lblEditorTitulo = new Guna2HtmlLabel();
            pnlHeader = new Guna2Panel();
            btnAtualizar = new Guna2Button();
            btnNovo = new Guna2Button();
            lblApiInfo = new Guna2HtmlLabel();
            lblResumo = new Guna2HtmlLabel();
            lblDescricao = new Guna2HtmlLabel();
            lblTitulo = new Guna2HtmlLabel();
            pnlPagina.SuspendLayout();
            pnlCard.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
            splitMain.Panel1.SuspendLayout();
            splitMain.Panel2.SuspendLayout();
            splitMain.SuspendLayout();
            pnlTabela.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPedidos).BeginInit();
            pnlEditor.SuspendLayout();
            pnlHeader.SuspendLayout();
            SuspendLayout();
            pnlPagina.BackColor = Color.FromArgb(33, 29, 85);
            pnlPagina.Controls.Add(pnlCard);
            pnlPagina.Dock = DockStyle.Fill;
            pnlPagina.FillColor = Color.FromArgb(33, 29, 85);
            pnlPagina.Location = new Point(0, 0);
            pnlPagina.Name = "pnlPagina";
            pnlPagina.Padding = new Padding(24);
            pnlPagina.Size = new Size(1140, 694);
            pnlPagina.TabIndex = 0;
            pnlCard.BorderRadius = 18;
            pnlCard.Controls.Add(splitMain);
            pnlCard.Controls.Add(pnlHeader);
            pnlCard.Dock = DockStyle.Fill;
            pnlCard.FillColor = Color.FromArgb(245, 247, 252);
            pnlCard.Location = new Point(24, 24);
            pnlCard.Name = "pnlCard";
            pnlCard.ShadowDecoration.BorderRadius = 18;
            pnlCard.ShadowDecoration.Depth = 10;
            pnlCard.ShadowDecoration.Enabled = true;
            pnlCard.Size = new Size(1092, 646);
            pnlCard.TabIndex = 0;
            splitMain.Dock = DockStyle.Fill;
            splitMain.Location = new Point(0, 122);
            splitMain.Name = "splitMain";
            splitMain.Panel1.Controls.Add(pnlTabela);
            splitMain.Panel2.Controls.Add(pnlEditor);
            splitMain.Size = new Size(1092, 524);
            splitMain.SplitterDistance = 684;
            splitMain.TabIndex = 1;
            pnlTabela.Controls.Add(dgvPedidos);
            pnlTabela.Dock = DockStyle.Fill;
            pnlTabela.FillColor = Color.Transparent;
            pnlTabela.Location = new Point(0, 0);
            pnlTabela.Name = "pnlTabela";
            pnlTabela.Padding = new Padding(18, 0, 12, 18);
            pnlTabela.Size = new Size(684, 524);
            pnlTabela.TabIndex = 0;
            dgvPedidos.AllowUserToAddRows = false;
            dgvPedidos.AllowUserToDeleteRows = false;
            dgvPedidos.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = Color.White;
            dgvPedidos.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvPedidos.BackgroundColor = Color.White;
            dgvPedidos.BorderStyle = BorderStyle.None;
            dgvPedidos.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvPedidos.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.FromArgb(241, 245, 249);
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.FromArgb(93, 104, 128);
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(241, 245, 249);
            dataGridViewCellStyle2.SelectionForeColor = Color.FromArgb(93, 104, 128);
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvPedidos.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvPedidos.ColumnHeadersHeight = 42;
            dgvPedidos.Columns.AddRange(new DataGridViewColumn[] { colId, colData, colStatus, colCliente, colTotal, colEditar, colExcluir });
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI", 9.5F);
            dataGridViewCellStyle3.ForeColor = Color.FromArgb(43, 52, 69);
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(237, 242, 255);
            dataGridViewCellStyle3.SelectionForeColor = Color.FromArgb(43, 52, 69);
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvPedidos.DefaultCellStyle = dataGridViewCellStyle3;
            dgvPedidos.Dock = DockStyle.Fill;
            dgvPedidos.GridColor = Color.FromArgb(233, 238, 245);
            dgvPedidos.Location = new Point(18, 0);
            dgvPedidos.MultiSelect = false;
            dgvPedidos.Name = "dgvPedidos";
            dgvPedidos.ReadOnly = true;
            dgvPedidos.RowHeadersVisible = false;
            dgvPedidos.RowTemplate.Height = 44;
            dgvPedidos.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvPedidos.Size = new Size(654, 506);
            dgvPedidos.TabIndex = 0;
            dgvPedidos.ThemeStyle.AlternatingRowsStyle.BackColor = Color.White;
            dgvPedidos.ThemeStyle.AlternatingRowsStyle.Font = null;
            dgvPedidos.ThemeStyle.AlternatingRowsStyle.ForeColor = Color.Empty;
            dgvPedidos.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = Color.Empty;
            dgvPedidos.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = Color.Empty;
            dgvPedidos.ThemeStyle.BackColor = Color.White;
            dgvPedidos.ThemeStyle.GridColor = Color.FromArgb(233, 238, 245);
            dgvPedidos.ThemeStyle.HeaderStyle.BackColor = Color.FromArgb(241, 245, 249);
            dgvPedidos.ThemeStyle.HeaderStyle.BorderStyle = DataGridViewHeaderBorderStyle.None;
            dgvPedidos.ThemeStyle.HeaderStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvPedidos.ThemeStyle.HeaderStyle.ForeColor = Color.FromArgb(93, 104, 128);
            dgvPedidos.ThemeStyle.HeaderStyle.HeaightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvPedidos.ThemeStyle.HeaderStyle.Height = 42;
            dgvPedidos.ThemeStyle.ReadOnly = true;
            dgvPedidos.ThemeStyle.RowsStyle.BackColor = Color.White;
            dgvPedidos.ThemeStyle.RowsStyle.BorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvPedidos.ThemeStyle.RowsStyle.Font = new Font("Segoe UI", 9.5F);
            dgvPedidos.ThemeStyle.RowsStyle.ForeColor = Color.FromArgb(43, 52, 69);
            dgvPedidos.ThemeStyle.RowsStyle.Height = 44;
            dgvPedidos.ThemeStyle.RowsStyle.SelectionBackColor = Color.FromArgb(237, 242, 255);
            dgvPedidos.ThemeStyle.RowsStyle.SelectionForeColor = Color.FromArgb(43, 52, 69);
            dgvPedidos.CellClick += dgvPedidos_CellClick;
            dgvPedidos.SelectionChanged += dgvPedidos_SelectionChanged;
            colId.FillWeight = 75F;
            colId.HeaderText = "ID";
            colId.Name = "colId";
            colId.ReadOnly = true;
            colData.FillWeight = 130F;
            colData.HeaderText = "DATA";
            colData.Name = "colData";
            colData.ReadOnly = true;
            colStatus.FillWeight = 120F;
            colStatus.HeaderText = "STATUS";
            colStatus.Name = "colStatus";
            colStatus.ReadOnly = true;
            colCliente.FillWeight = 150F;
            colCliente.HeaderText = "CLIENTE";
            colCliente.Name = "colCliente";
            colCliente.ReadOnly = true;
            colTotal.FillWeight = 120F;
            colTotal.HeaderText = "TOTAL";
            colTotal.Name = "colTotal";
            colTotal.ReadOnly = true;
            colEditar.FillWeight = 80F;
            colEditar.HeaderText = "";
            colEditar.Name = "colEditar";
            colEditar.ReadOnly = true;
            colEditar.Text = "Editar";
            colEditar.UseColumnTextForButtonValue = true;
            colExcluir.FillWeight = 80F;
            colExcluir.HeaderText = "";
            colExcluir.Name = "colExcluir";
            colExcluir.ReadOnly = true;
            colExcluir.Text = "Excluir";
            colExcluir.UseColumnTextForButtonValue = true;
            pnlEditor.BackColor = Color.Transparent;
            pnlEditor.Controls.Add(btnExcluir);
            pnlEditor.Controls.Add(btnSalvar);
            pnlEditor.Controls.Add(txtObservacao);
            pnlEditor.Controls.Add(lblObservacao);
            pnlEditor.Controls.Add(txtBairro);
            pnlEditor.Controls.Add(lblBairro);
            pnlEditor.Controls.Add(txtEndereco);
            pnlEditor.Controls.Add(lblEndereco);
            pnlEditor.Controls.Add(cboPagamento);
            pnlEditor.Controls.Add(lblPagamento);
            pnlEditor.Controls.Add(txtValor);
            pnlEditor.Controls.Add(lblValor);
            pnlEditor.Controls.Add(cboCliente);
            pnlEditor.Controls.Add(lblCliente);
            pnlEditor.Controls.Add(cboStatus);
            pnlEditor.Controls.Add(lblStatus);
            pnlEditor.Controls.Add(dtpData);
            pnlEditor.Controls.Add(lblData);
            pnlEditor.Controls.Add(txtCodigo);
            pnlEditor.Controls.Add(lblCodigo);
            pnlEditor.Controls.Add(lblEditorTitulo);
            pnlEditor.Dock = DockStyle.Fill;
            pnlEditor.FillColor = Color.White;
            pnlEditor.Location = new Point(0, 0);
            pnlEditor.Name = "pnlEditor";
            pnlEditor.Padding = new Padding(14, 0, 18, 18);
            pnlEditor.Size = new Size(404, 524);
            pnlEditor.TabIndex = 0;
            btnExcluir.BorderRadius = 10;
            btnExcluir.DisabledState.BorderColor = Color.DarkGray;
            btnExcluir.DisabledState.CustomBorderColor = Color.DarkGray;
            btnExcluir.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnExcluir.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnExcluir.FillColor = Color.FromArgb(239, 68, 68);
            btnExcluir.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnExcluir.ForeColor = Color.White;
            btnExcluir.Location = new Point(209, 480);
            btnExcluir.Name = "btnExcluir";
            btnExcluir.Size = new Size(165, 34);
            btnExcluir.TabIndex = 20;
            btnExcluir.Text = "Excluir pedido";
            btnExcluir.Click += btnExcluir_Click;
            btnSalvar.BorderRadius = 10;
            btnSalvar.DisabledState.BorderColor = Color.DarkGray;
            btnSalvar.DisabledState.CustomBorderColor = Color.DarkGray;
            btnSalvar.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnSalvar.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnSalvar.FillColor = Color.FromArgb(37, 99, 235);
            btnSalvar.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnSalvar.ForeColor = Color.White;
            btnSalvar.Location = new Point(28, 480);
            btnSalvar.Name = "btnSalvar";
            btnSalvar.Size = new Size(165, 34);
            btnSalvar.TabIndex = 19;
            btnSalvar.Text = "Salvar";
            btnSalvar.Click += btnSalvar_Click;
            txtObservacao.BorderRadius = 10;
            txtObservacao.Cursor = Cursors.IBeam;
            txtObservacao.DefaultText = "";
            txtObservacao.DisabledState.BorderColor = Color.FromArgb(208, 208, 208);
            txtObservacao.DisabledState.FillColor = Color.FromArgb(226, 226, 226);
            txtObservacao.DisabledState.ForeColor = Color.FromArgb(138, 138, 138);
            txtObservacao.DisabledState.PlaceholderForeColor = Color.FromArgb(138, 138, 138);
            txtObservacao.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            txtObservacao.Font = new Font("Segoe UI", 10F);
            txtObservacao.HoverState.BorderColor = Color.FromArgb(94, 148, 255);
            txtObservacao.Location = new Point(28, 420);
            txtObservacao.Margin = new Padding(3, 4, 3, 4);
            txtObservacao.Multiline = true;
            txtObservacao.Name = "txtObservacao";
            txtObservacao.PlaceholderText = "Detalhes do pedido";
            txtObservacao.SelectedText = "";
            txtObservacao.Size = new Size(346, 52);
            txtObservacao.TabIndex = 18;
            lblObservacao.BackColor = Color.Transparent;
            lblObservacao.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblObservacao.ForeColor = Color.FromArgb(70, 81, 102);
            lblObservacao.Location = new Point(28, 396);
            lblObservacao.Name = "lblObservacao";
            lblObservacao.Size = new Size(78, 19);
            lblObservacao.TabIndex = 17;
            lblObservacao.Text = "Observação";
            txtBairro.BorderRadius = 10;
            txtBairro.Cursor = Cursors.IBeam;
            txtBairro.DefaultText = "";
            txtBairro.DisabledState.BorderColor = Color.FromArgb(208, 208, 208);
            txtBairro.DisabledState.FillColor = Color.FromArgb(226, 226, 226);
            txtBairro.DisabledState.ForeColor = Color.FromArgb(138, 138, 138);
            txtBairro.DisabledState.PlaceholderForeColor = Color.FromArgb(138, 138, 138);
            txtBairro.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            txtBairro.Font = new Font("Segoe UI", 10F);
            txtBairro.HoverState.BorderColor = Color.FromArgb(94, 148, 255);
            txtBairro.Location = new Point(28, 350);
            txtBairro.Margin = new Padding(3, 4, 3, 4);
            txtBairro.Name = "txtBairro";
            txtBairro.PlaceholderText = "Bairro";
            txtBairro.SelectedText = "";
            txtBairro.Size = new Size(346, 40);
            txtBairro.TabIndex = 16;
            lblBairro.BackColor = Color.Transparent;
            lblBairro.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblBairro.ForeColor = Color.FromArgb(70, 81, 102);
            lblBairro.Location = new Point(28, 326);
            lblBairro.Name = "lblBairro";
            lblBairro.Size = new Size(43, 19);
            lblBairro.TabIndex = 15;
            lblBairro.Text = "Bairro";
            txtEndereco.BorderRadius = 10;
            txtEndereco.Cursor = Cursors.IBeam;
            txtEndereco.DefaultText = "";
            txtEndereco.DisabledState.BorderColor = Color.FromArgb(208, 208, 208);
            txtEndereco.DisabledState.FillColor = Color.FromArgb(226, 226, 226);
            txtEndereco.DisabledState.ForeColor = Color.FromArgb(138, 138, 138);
            txtEndereco.DisabledState.PlaceholderForeColor = Color.FromArgb(138, 138, 138);
            txtEndereco.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            txtEndereco.Font = new Font("Segoe UI", 10F);
            txtEndereco.HoverState.BorderColor = Color.FromArgb(94, 148, 255);
            txtEndereco.Location = new Point(28, 280);
            txtEndereco.Margin = new Padding(3, 4, 3, 4);
            txtEndereco.Name = "txtEndereco";
            txtEndereco.PlaceholderText = "Rua, número e complemento";
            txtEndereco.SelectedText = "";
            txtEndereco.Size = new Size(346, 40);
            txtEndereco.TabIndex = 14;
            lblEndereco.BackColor = Color.Transparent;
            lblEndereco.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblEndereco.ForeColor = Color.FromArgb(70, 81, 102);
            lblEndereco.Location = new Point(28, 256);
            lblEndereco.Name = "lblEndereco";
            lblEndereco.Size = new Size(65, 19);
            lblEndereco.TabIndex = 13;
            lblEndereco.Text = "Endereço";
            cboPagamento.BackColor = Color.Transparent;
            cboPagamento.BorderRadius = 10;
            cboPagamento.DrawMode = DrawMode.OwnerDrawFixed;
            cboPagamento.DropDownStyle = ComboBoxStyle.DropDownList;
            cboPagamento.FocusedColor = Color.FromArgb(94, 148, 255);
            cboPagamento.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            cboPagamento.Font = new Font("Segoe UI", 10F);
            cboPagamento.ForeColor = Color.FromArgb(68, 88, 112);
            cboPagamento.ItemHeight = 30;
            cboPagamento.Location = new Point(197, 210);
            cboPagamento.Name = "cboPagamento";
            cboPagamento.Size = new Size(177, 36);
            cboPagamento.TabIndex = 12;
            lblPagamento.BackColor = Color.Transparent;
            lblPagamento.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblPagamento.ForeColor = Color.FromArgb(70, 81, 102);
            lblPagamento.Location = new Point(197, 186);
            lblPagamento.Name = "lblPagamento";
            lblPagamento.Size = new Size(80, 19);
            lblPagamento.TabIndex = 11;
            lblPagamento.Text = "Pagamento";
            txtValor.BorderRadius = 10;
            txtValor.Cursor = Cursors.IBeam;
            txtValor.DefaultText = "";
            txtValor.DisabledState.BorderColor = Color.FromArgb(208, 208, 208);
            txtValor.DisabledState.FillColor = Color.FromArgb(226, 226, 226);
            txtValor.DisabledState.ForeColor = Color.FromArgb(138, 138, 138);
            txtValor.DisabledState.PlaceholderForeColor = Color.FromArgb(138, 138, 138);
            txtValor.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            txtValor.Font = new Font("Segoe UI", 10F);
            txtValor.HoverState.BorderColor = Color.FromArgb(94, 148, 255);
            txtValor.Location = new Point(28, 210);
            txtValor.Margin = new Padding(3, 4, 3, 4);
            txtValor.Name = "txtValor";
            txtValor.PlaceholderText = "0,00";
            txtValor.SelectedText = "";
            txtValor.Size = new Size(151, 40);
            txtValor.TabIndex = 10;
            lblValor.BackColor = Color.Transparent;
            lblValor.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblValor.ForeColor = Color.FromArgb(70, 81, 102);
            lblValor.Location = new Point(28, 186);
            lblValor.Name = "lblValor";
            lblValor.Size = new Size(35, 19);
            lblValor.TabIndex = 9;
            lblValor.Text = "Valor";
            cboCliente.BackColor = Color.Transparent;
            cboCliente.BorderRadius = 10;
            cboCliente.DrawMode = DrawMode.OwnerDrawFixed;
            cboCliente.DropDownStyle = ComboBoxStyle.DropDownList;
            cboCliente.FocusedColor = Color.FromArgb(94, 148, 255);
            cboCliente.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            cboCliente.Font = new Font("Segoe UI", 10F);
            cboCliente.ForeColor = Color.FromArgb(68, 88, 112);
            cboCliente.ItemHeight = 30;
            cboCliente.Location = new Point(197, 140);
            cboCliente.Name = "cboCliente";
            cboCliente.Size = new Size(177, 36);
            cboCliente.TabIndex = 8;
            lblCliente.BackColor = Color.Transparent;
            lblCliente.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblCliente.ForeColor = Color.FromArgb(70, 81, 102);
            lblCliente.Location = new Point(197, 116);
            lblCliente.Name = "lblCliente";
            lblCliente.Size = new Size(47, 19);
            lblCliente.TabIndex = 7;
            lblCliente.Text = "Cliente";
            cboStatus.BackColor = Color.Transparent;
            cboStatus.BorderRadius = 10;
            cboStatus.DrawMode = DrawMode.OwnerDrawFixed;
            cboStatus.DropDownStyle = ComboBoxStyle.DropDownList;
            cboStatus.FocusedColor = Color.FromArgb(94, 148, 255);
            cboStatus.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            cboStatus.Font = new Font("Segoe UI", 10F);
            cboStatus.ForeColor = Color.FromArgb(68, 88, 112);
            cboStatus.ItemHeight = 30;
            cboStatus.Location = new Point(28, 140);
            cboStatus.Name = "cboStatus";
            cboStatus.Size = new Size(151, 36);
            cboStatus.TabIndex = 6;
            lblStatus.BackColor = Color.Transparent;
            lblStatus.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblStatus.ForeColor = Color.FromArgb(70, 81, 102);
            lblStatus.Location = new Point(28, 116);
            lblStatus.Name = "lblStatus";
            lblStatus.Size = new Size(42, 19);
            lblStatus.TabIndex = 5;
            lblStatus.Text = "Status";
            dtpData.BorderRadius = 10;
            dtpData.Checked = true;
            dtpData.FillColor = Color.FromArgb(244, 247, 250);
            dtpData.Font = new Font("Segoe UI", 9.75F);
            dtpData.Format = DateTimePickerFormat.Custom;
            dtpData.Location = new Point(197, 70);
            dtpData.MaxDate = new DateTime(2099, 12, 31, 0, 0, 0, 0);
            dtpData.MinDate = new DateTime(2000, 1, 1, 0, 0, 0, 0);
            dtpData.Name = "dtpData";
            dtpData.Size = new Size(177, 40);
            dtpData.TabIndex = 4;
            dtpData.Value = new DateTime(2026, 4, 10, 0, 0, 0, 0);
            lblData.BackColor = Color.Transparent;
            lblData.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblData.ForeColor = Color.FromArgb(70, 81, 102);
            lblData.Location = new Point(197, 46);
            lblData.Name = "lblData";
            lblData.Size = new Size(31, 19);
            lblData.TabIndex = 3;
            lblData.Text = "Data";
            txtCodigo.BorderRadius = 10;
            txtCodigo.Cursor = Cursors.IBeam;
            txtCodigo.DefaultText = "";
            txtCodigo.DisabledState.BorderColor = Color.FromArgb(208, 208, 208);
            txtCodigo.DisabledState.FillColor = Color.FromArgb(226, 226, 226);
            txtCodigo.DisabledState.ForeColor = Color.FromArgb(138, 138, 138);
            txtCodigo.DisabledState.PlaceholderForeColor = Color.FromArgb(138, 138, 138);
            txtCodigo.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            txtCodigo.Font = new Font("Segoe UI", 10F);
            txtCodigo.HoverState.BorderColor = Color.FromArgb(94, 148, 255);
            txtCodigo.Location = new Point(28, 70);
            txtCodigo.Margin = new Padding(3, 4, 3, 4);
            txtCodigo.Name = "txtCodigo";
            txtCodigo.PlaceholderText = "";
            txtCodigo.ReadOnly = true;
            txtCodigo.SelectedText = "";
            txtCodigo.Size = new Size(151, 40);
            txtCodigo.TabIndex = 2;
            lblCodigo.BackColor = Color.Transparent;
            lblCodigo.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblCodigo.ForeColor = Color.FromArgb(70, 81, 102);
            lblCodigo.Location = new Point(28, 46);
            lblCodigo.Name = "lblCodigo";
            lblCodigo.Size = new Size(52, 19);
            lblCodigo.TabIndex = 1;
            lblCodigo.Text = "Pedido";
            lblEditorTitulo.BackColor = Color.Transparent;
            lblEditorTitulo.Font = new Font("Segoe UI Semibold", 15F, FontStyle.Bold);
            lblEditorTitulo.ForeColor = Color.FromArgb(26, 36, 56);
            lblEditorTitulo.Location = new Point(22, 8);
            lblEditorTitulo.Name = "lblEditorTitulo";
            lblEditorTitulo.Size = new Size(182, 30);
            lblEditorTitulo.TabIndex = 0;
            lblEditorTitulo.Text = "Detalhes do pedido";
            pnlHeader.Controls.Add(btnAtualizar);
            pnlHeader.Controls.Add(btnNovo);
            pnlHeader.Controls.Add(lblApiInfo);
            pnlHeader.Controls.Add(lblResumo);
            pnlHeader.Controls.Add(lblDescricao);
            pnlHeader.Controls.Add(lblTitulo);
            pnlHeader.Dock = DockStyle.Top;
            pnlHeader.FillColor = Color.White;
            pnlHeader.Location = new Point(0, 0);
            pnlHeader.Name = "pnlHeader";
            pnlHeader.Padding = new Padding(24, 22, 24, 18);
            pnlHeader.Size = new Size(1092, 122);
            pnlHeader.TabIndex = 0;
            btnAtualizar.BorderRadius = 10;
            btnAtualizar.DisabledState.BorderColor = Color.DarkGray;
            btnAtualizar.DisabledState.CustomBorderColor = Color.DarkGray;
            btnAtualizar.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnAtualizar.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnAtualizar.FillColor = Color.FromArgb(15, 23, 42);
            btnAtualizar.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnAtualizar.ForeColor = Color.White;
            btnAtualizar.Location = new Point(888, 28);
            btnAtualizar.Name = "btnAtualizar";
            btnAtualizar.Size = new Size(84, 40);
            btnAtualizar.TabIndex = 5;
            btnAtualizar.Text = "Atualizar";
            btnAtualizar.Click += btnAtualizar_Click;
            btnNovo.BorderRadius = 10;
            btnNovo.DisabledState.BorderColor = Color.DarkGray;
            btnNovo.DisabledState.CustomBorderColor = Color.DarkGray;
            btnNovo.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnNovo.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnNovo.FillColor = Color.FromArgb(37, 99, 235);
            btnNovo.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnNovo.ForeColor = Color.White;
            btnNovo.Location = new Point(978, 28);
            btnNovo.Name = "btnNovo";
            btnNovo.Size = new Size(90, 40);
            btnNovo.TabIndex = 4;
            btnNovo.Text = "Novo";
            btnNovo.Click += btnNovo_Click;
            lblApiInfo.BackColor = Color.Transparent;
            lblApiInfo.ForeColor = Color.FromArgb(107, 114, 128);
            lblApiInfo.Location = new Point(24, 82);
            lblApiInfo.Name = "lblApiInfo";
            lblApiInfo.Size = new Size(127, 19);
            lblApiInfo.TabIndex = 3;
            lblApiInfo.Text = "API: http://localhost:5207/";
            lblResumo.BackColor = Color.Transparent;
            lblResumo.ForeColor = Color.FromArgb(34, 197, 94);
            lblResumo.Location = new Point(24, 63);
            lblResumo.Name = "lblResumo";
            lblResumo.Size = new Size(104, 19);
            lblResumo.TabIndex = 2;
            lblResumo.Text = "Carregando dados";
            lblDescricao.BackColor = Color.Transparent;
            lblDescricao.ForeColor = Color.FromArgb(107, 114, 128);
            lblDescricao.Location = new Point(24, 38);
            lblDescricao.Name = "lblDescricao";
            lblDescricao.Size = new Size(281, 19);
            lblDescricao.TabIndex = 1;
            lblDescricao.Text = "Visualize e gerencie os pedidos feitos pelos usuários";
            lblTitulo.BackColor = Color.Transparent;
            lblTitulo.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.FromArgb(26, 36, 56);
            lblTitulo.Location = new Point(24, 4);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(171, 34);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Gestão de Pedidos";
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Controls.Add(pnlPagina);
            FormBorderStyle = FormBorderStyle.None;
            Name = "frmPedidos";
            Text = "frmPedidos";
            pnlPagina.ResumeLayout(false);
            pnlCard.ResumeLayout(false);
            splitMain.Panel1.ResumeLayout(false);
            splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
            splitMain.ResumeLayout(false);
            pnlTabela.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvPedidos).EndInit();
            pnlEditor.ResumeLayout(false);
            pnlEditor.PerformLayout();
            pnlHeader.ResumeLayout(false);
            pnlHeader.PerformLayout();
            ResumeLayout(false);
        }
    }
}
