#nullable enable
using Guna.UI2.WinForms;

namespace acaiGalatico.UI.Forms
{
    partial class frmPrincipal
    {
        private System.ComponentModel.IContainer? components = null;
        private Guna2BorderlessForm borderlessForm;
        private Guna2ShadowForm shadowForm;
        private Guna2Panel pnlSidebar;
        private Guna2Panel pnlTopo;
        private Guna2Panel pnlConteudo;
        private Guna2HtmlLabel lblMarca;
        private Guna2HtmlLabel lblPainel;
        private Guna2HtmlLabel lblPaginaTitulo;
        private Guna2HtmlLabel lblUsuario;
        private Guna2Button btnDashboard;
        private Guna2Button btnPedidos;
        private Guna2Button btnProdutos;
        private Guna2Button btnClientes;
        private Guna2Button btnEditarSite;
        private Guna2Button btnCardapio;
        private Guna2Button btnSair;
        private Guna2CirclePictureBox picUsuario;
        private Guna2ControlBox ctlClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            borderlessForm = new Guna2BorderlessForm(components);
            shadowForm = new Guna2ShadowForm(components);
            pnlSidebar = new Guna2Panel();
            btnSair = new Guna2Button();
            btnCardapio = new Guna2Button();
            btnEditarSite = new Guna2Button();
            btnClientes = new Guna2Button();
            btnProdutos = new Guna2Button();
            btnPedidos = new Guna2Button();
            btnDashboard = new Guna2Button();
            lblPainel = new Guna2HtmlLabel();
            lblMarca = new Guna2HtmlLabel();
            pnlTopo = new Guna2Panel();
            ctlClose = new Guna2ControlBox();
            picUsuario = new Guna2CirclePictureBox();
            lblUsuario = new Guna2HtmlLabel();
            lblPaginaTitulo = new Guna2HtmlLabel();
            pnlConteudo = new Guna2Panel();
            pnlSidebar.SuspendLayout();
            pnlTopo.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picUsuario).BeginInit();
            SuspendLayout();
            borderlessForm.BorderRadius = 18;
            borderlessForm.ContainerControl = this;
            borderlessForm.DockIndicatorTransparencyValue = 0.6D;
            borderlessForm.TransparentWhileDrag = true;
            shadowForm.TargetForm = this;
            pnlSidebar.BackColor = Color.FromArgb(35, 52, 74);
            pnlSidebar.Controls.Add(btnSair);
            pnlSidebar.Controls.Add(btnCardapio);
            pnlSidebar.Controls.Add(btnEditarSite);
            pnlSidebar.Controls.Add(btnClientes);
            pnlSidebar.Controls.Add(btnProdutos);
            pnlSidebar.Controls.Add(btnPedidos);
            pnlSidebar.Controls.Add(btnDashboard);
            pnlSidebar.Controls.Add(lblPainel);
            pnlSidebar.Controls.Add(lblMarca);
            pnlSidebar.Dock = DockStyle.Left;
            pnlSidebar.FillColor = Color.FromArgb(35, 52, 74);
            pnlSidebar.Location = new Point(0, 0);
            pnlSidebar.Name = "pnlSidebar";
            pnlSidebar.Size = new Size(224, 768);
            pnlSidebar.TabIndex = 0;
            btnSair.Animated = true;
            btnSair.BorderRadius = 10;
            btnSair.DisabledState.BorderColor = Color.DarkGray;
            btnSair.DisabledState.CustomBorderColor = Color.DarkGray;
            btnSair.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnSair.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnSair.FillColor = Color.FromArgb(196, 68, 86);
            btnSair.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnSair.ForeColor = Color.White;
            btnSair.Location = new Point(24, 696);
            btnSair.Name = "btnSair";
            btnSair.Size = new Size(176, 42);
            btnSair.TabIndex = 8;
            btnSair.Text = "Sair";
            btnSair.Click += btnSair_Click;
            btnCardapio.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton;
            btnCardapio.CheckedState.FillColor = Color.FromArgb(60, 74, 109);
            btnCardapio.DisabledState.BorderColor = Color.DarkGray;
            btnCardapio.DisabledState.CustomBorderColor = Color.DarkGray;
            btnCardapio.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnCardapio.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnCardapio.FillColor = Color.Transparent;
            btnCardapio.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnCardapio.ForeColor = Color.FromArgb(219, 228, 243);
            btnCardapio.HoverState.FillColor = Color.FromArgb(60, 74, 109);
            btnCardapio.Location = new Point(12, 372);
            btnCardapio.Name = "btnCardapio";
            btnCardapio.Size = new Size(200, 44);
            btnCardapio.TabIndex = 7;
            btnCardapio.Text = "Cardápio";
            btnCardapio.TextAlign = HorizontalAlignment.Left;
            btnCardapio.Click += btnCardapio_Click;
            btnEditarSite.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton;
            btnEditarSite.CheckedState.FillColor = Color.FromArgb(60, 74, 109);
            btnEditarSite.DisabledState.BorderColor = Color.DarkGray;
            btnEditarSite.DisabledState.CustomBorderColor = Color.DarkGray;
            btnEditarSite.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnEditarSite.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnEditarSite.FillColor = Color.Transparent;
            btnEditarSite.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnEditarSite.ForeColor = Color.FromArgb(219, 228, 243);
            btnEditarSite.HoverState.FillColor = Color.FromArgb(60, 74, 109);
            btnEditarSite.Location = new Point(12, 324);
            btnEditarSite.Name = "btnEditarSite";
            btnEditarSite.Size = new Size(200, 44);
            btnEditarSite.TabIndex = 6;
            btnEditarSite.Text = "Editar Site";
            btnEditarSite.TextAlign = HorizontalAlignment.Left;
            btnEditarSite.Click += btnEditarSite_Click;
            btnClientes.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton;
            btnClientes.CheckedState.FillColor = Color.FromArgb(60, 74, 109);
            btnClientes.DisabledState.BorderColor = Color.DarkGray;
            btnClientes.DisabledState.CustomBorderColor = Color.DarkGray;
            btnClientes.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnClientes.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnClientes.FillColor = Color.Transparent;
            btnClientes.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnClientes.ForeColor = Color.FromArgb(219, 228, 243);
            btnClientes.HoverState.FillColor = Color.FromArgb(60, 74, 109);
            btnClientes.Location = new Point(12, 276);
            btnClientes.Name = "btnClientes";
            btnClientes.Size = new Size(200, 44);
            btnClientes.TabIndex = 5;
            btnClientes.Text = "Clientes";
            btnClientes.TextAlign = HorizontalAlignment.Left;
            btnClientes.Click += btnClientes_Click;
            btnProdutos.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton;
            btnProdutos.CheckedState.FillColor = Color.FromArgb(60, 74, 109);
            btnProdutos.DisabledState.BorderColor = Color.DarkGray;
            btnProdutos.DisabledState.CustomBorderColor = Color.DarkGray;
            btnProdutos.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnProdutos.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnProdutos.FillColor = Color.Transparent;
            btnProdutos.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnProdutos.ForeColor = Color.FromArgb(219, 228, 243);
            btnProdutos.HoverState.FillColor = Color.FromArgb(60, 74, 109);
            btnProdutos.Location = new Point(12, 228);
            btnProdutos.Name = "btnProdutos";
            btnProdutos.Size = new Size(200, 44);
            btnProdutos.TabIndex = 4;
            btnProdutos.Text = "Produtos";
            btnProdutos.TextAlign = HorizontalAlignment.Left;
            btnProdutos.Click += btnProdutos_Click;
            btnPedidos.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton;
            btnPedidos.Checked = true;
            btnPedidos.CheckedState.FillColor = Color.FromArgb(60, 74, 109);
            btnPedidos.DisabledState.BorderColor = Color.DarkGray;
            btnPedidos.DisabledState.CustomBorderColor = Color.DarkGray;
            btnPedidos.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnPedidos.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnPedidos.FillColor = Color.FromArgb(60, 74, 109);
            btnPedidos.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnPedidos.ForeColor = Color.White;
            btnPedidos.HoverState.FillColor = Color.FromArgb(60, 74, 109);
            btnPedidos.Location = new Point(12, 180);
            btnPedidos.Name = "btnPedidos";
            btnPedidos.Size = new Size(200, 44);
            btnPedidos.TabIndex = 3;
            btnPedidos.Text = "Pedidos";
            btnPedidos.TextAlign = HorizontalAlignment.Left;
            btnPedidos.Click += btnPedidos_Click;
            btnDashboard.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton;
            btnDashboard.CheckedState.FillColor = Color.FromArgb(60, 74, 109);
            btnDashboard.DisabledState.BorderColor = Color.DarkGray;
            btnDashboard.DisabledState.CustomBorderColor = Color.DarkGray;
            btnDashboard.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnDashboard.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnDashboard.FillColor = Color.Transparent;
            btnDashboard.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnDashboard.ForeColor = Color.FromArgb(219, 228, 243);
            btnDashboard.HoverState.FillColor = Color.FromArgb(60, 74, 109);
            btnDashboard.Location = new Point(12, 132);
            btnDashboard.Name = "btnDashboard";
            btnDashboard.Size = new Size(200, 44);
            btnDashboard.TabIndex = 2;
            btnDashboard.Text = "Dashboard";
            btnDashboard.TextAlign = HorizontalAlignment.Left;
            btnDashboard.Click += btnDashboard_Click;
            lblPainel.BackColor = Color.Transparent;
            lblPainel.ForeColor = Color.FromArgb(170, 183, 205);
            lblPainel.Location = new Point(24, 76);
            lblPainel.Name = "lblPainel";
            lblPainel.Size = new Size(88, 19);
            lblPainel.TabIndex = 1;
            lblPainel.Text = "PAINEL ADMIN";
            lblMarca.BackColor = Color.Transparent;
            lblMarca.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold);
            lblMarca.ForeColor = Color.White;
            lblMarca.Location = new Point(24, 28);
            lblMarca.Name = "lblMarca";
            lblMarca.Size = new Size(134, 34);
            lblMarca.TabIndex = 0;
            lblMarca.Text = "Açaí Galático";
            pnlTopo.Controls.Add(ctlClose);
            pnlTopo.Controls.Add(picUsuario);
            pnlTopo.Controls.Add(lblUsuario);
            pnlTopo.Controls.Add(lblPaginaTitulo);
            pnlTopo.Dock = DockStyle.Top;
            pnlTopo.FillColor = Color.White;
            pnlTopo.Location = new Point(224, 0);
            pnlTopo.Name = "pnlTopo";
            pnlTopo.ShadowDecoration.Depth = 6;
            pnlTopo.ShadowDecoration.Enabled = true;
            pnlTopo.Size = new Size(1140, 74);
            pnlTopo.TabIndex = 1;
            ctlClose.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            ctlClose.FillColor = Color.Transparent;
            ctlClose.HoverState.FillColor = Color.FromArgb(244, 67, 54);
            ctlClose.HoverState.IconColor = Color.White;
            ctlClose.IconColor = Color.FromArgb(89, 103, 132);
            ctlClose.Location = new Point(1087, 14);
            ctlClose.Name = "ctlClose";
            ctlClose.Size = new Size(37, 29);
            ctlClose.TabIndex = 3;
            picUsuario.FillColor = Color.FromArgb(232, 236, 244);
            picUsuario.ImageRotate = 0F;
            picUsuario.Location = new Point(992, 18);
            picUsuario.Name = "picUsuario";
            picUsuario.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            picUsuario.Size = new Size(36, 36);
            picUsuario.TabIndex = 2;
            picUsuario.TabStop = false;
            lblUsuario.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            lblUsuario.BackColor = Color.Transparent;
            lblUsuario.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            lblUsuario.ForeColor = Color.FromArgb(72, 85, 115);
            lblUsuario.Location = new Point(874, 26);
            lblUsuario.Name = "lblUsuario";
            lblUsuario.Size = new Size(94, 19);
            lblUsuario.TabIndex = 1;
            lblUsuario.Text = "Administrador";
            lblPaginaTitulo.BackColor = Color.Transparent;
            lblPaginaTitulo.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold);
            lblPaginaTitulo.ForeColor = Color.FromArgb(26, 36, 56);
            lblPaginaTitulo.Location = new Point(28, 20);
            lblPaginaTitulo.Name = "lblPaginaTitulo";
            lblPaginaTitulo.Size = new Size(84, 34);
            lblPaginaTitulo.TabIndex = 0;
            lblPaginaTitulo.Text = "Pedidos";
            pnlConteudo.BackColor = Color.FromArgb(33, 29, 85);
            pnlConteudo.Dock = DockStyle.Fill;
            pnlConteudo.FillColor = Color.FromArgb(33, 29, 85);
            pnlConteudo.Location = new Point(224, 74);
            pnlConteudo.Name = "pnlConteudo";
            pnlConteudo.Padding = new Padding(20);
            pnlConteudo.Size = new Size(1140, 694);
            pnlConteudo.TabIndex = 2;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(241, 245, 249);
            ClientSize = new Size(1364, 768);
            Controls.Add(pnlConteudo);
            Controls.Add(pnlTopo);
            Controls.Add(pnlSidebar);
            FormBorderStyle = FormBorderStyle.None;
            Name = "frmPrincipal";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Painel Admin";
            WindowState = FormWindowState.Maximized;
            pnlSidebar.ResumeLayout(false);
            pnlSidebar.PerformLayout();
            pnlTopo.ResumeLayout(false);
            pnlTopo.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)picUsuario).EndInit();
            ResumeLayout(false);
        }
    }
}
